Dev
tchaura/project-oop pull request #1
Opened 2022-03-27 21:42 UTC by tchaura

2022-03-27 21:45 UTC, tchaura commented
У меня на четвертом уровне бред какой то с базой данных выходит. Выдает синтаксическую ошибку при попытке добавить новую запись в бдшку через тот код, что у меня

2022-03-27 21:48 UTC, DenVilk commented
Для начала разбейте main на модули, как я говорил на занятии.

2022-03-27 21:54 UTC, DenVilk commented
Также не вижу применения инкапсуляции. Также попрошу вас добавить комментарии согласно соглашениям PEP.

2022-03-28 19:50 UTC, tchaura commented
Так а что насчет sql? Мне бы понять, в чем проблема, а то после разбиения на модули придется еще больше запариваться

2022-03-28 19:58 UTC, DenVilk commented
Я уже говорил что буду принимать каждый уровень отдельно. В первом уровне sql нет.

2022-03-31 20:34 UTC, tchaura commented
@DenVilk сделал первый уровень

2022-04-02 09:02 UTC, DenVilk requested changes

2022-04-02 09:02 UTC, DenVilk commented on utils.py
> +        num = list(receiptsdict.keys())[-1] + 1
Почему не ```len(recieptdict.keys()) + 1```?
И в целом, почему словарь, а не список?

2022-04-02 09:02 UTC, DenVilk commented on utils.py
> +                isfound = True
Мы нашли нужную квитанцию, но продолжаем искать дальше?

2022-04-02 09:02 UTC, DenVilk commented on utils.py
> +    typeofproduct = None
Почему переменная называется ```typeofproduct``` если она хранит девайс, который чинят?

2022-04-02 09:02 UTC, DenVilk commented on utils.py
> +from devices import *
Рекомендуется не использовать оператор * для импорта всего модуля, а использовать перечисление всех необходимых объектов.

2022-04-02 14:04 UTC, tchaura commented on utils.py
> +        num = list(receiptsdict.keys())[-1] + 1
словарь, по моему удобнее, отдельно номер квитанции, отдельно - информация о ней

2022-04-02 14:09 UTC, tchaura commented on utils.py
> +                isfound = True
Человек с теми же инициалами может зарегистрировать несколько заявок

2022-04-02 14:13 UTC, DenVilk commented on utils.py
> +        num = list(receiptsdict.keys())[-1] + 1
А чем от списка отличается?
Индекс - номер, значение - информация

2022-04-02 14:42 UTC, tchaura commented on utils.py
> +    typeofproduct = None
переименовал на `repairingdevice`

2022-04-02 14:42 UTC, tchaura commented on utils.py
> +from devices import *
исправил

2022-04-02 14:43 UTC, tchaura commented on utils.py
> +                isfound = True
также немного подправил поиск по инициалам

2022-04-02 14:49 UTC, tchaura commented on utils.py
> +        num = list(receiptsdict.keys())[-1] + 1
при удалении номера сдвигаться будут

2022-04-02 16:52 UTC, tchaura commented
@DenVilk Сделал необходимые правки

2022-04-02 17:13 UTC, DenVilk commented on utils.py
> +    typeofproduct = None
посмотрите последнее видео с занятия, там разобрали тему именования в python.

2022-04-02 20:02 UTC, tchaura commented on utils.py
> +    typeofproduct = None
я в последнем коммите вроде бы изменил все как необходимо

2022-04-04 11:49 UTC, tchaura commented on utils.py
> +    typeofproduct = None
@DenVilk можно ли переходить на следующий уровень?

2022-04-04 14:35 UTC, DenVilk approved these changes
Добавьте docstrings согласно PEP 257. Можете переходить на следующий уровень.

2022-04-04 15:45 UTC, merged